ALTER TABLE "OrganizerIntegration" ADD COLUMN "secretCiphertext" TEXT;
ALTER TYPE "SortexAdStatus" ADD VALUE IF NOT EXISTS 'LIVE_ACTIVE';
ALTER TABLE "SortexAdCampaign"
  ADD COLUMN "externalCampaignId" TEXT,
  ADD COLUMN "externalAdSetId" TEXT,
  ADD COLUMN "externalCreativeId" TEXT,
  ADD COLUMN "externalAdId" TEXT,
  ADD COLUMN "spent" DECIMAL(16,2) NOT NULL DEFAULT 0,
  ADD COLUMN "reach" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "impressions" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "ctr" DECIMAL(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN "cpm" DECIMAL(14,4) NOT NULL DEFAULT 0,
  ADD COLUMN "cpc" DECIMAL(14,4) NOT NULL DEFAULT 0,
  ADD COLUMN "lastSyncedAt" TIMESTAMP(3);
