"use client";

import { useEffect, useState } from "react";
import { Copy, Share2 } from "lucide-react";
import { affiliateDashboard } from "@/lib/affiliates/client";

type Dashboard={memberships:number;clicks:number;conversions:number;pending:number;available:number;paid:number;links:Array<{id:string;url:string;clicks:number;conversions:number;campaign?:{title?:string};commissionPercentage?:number}>;recentConversions:unknown[]};

export default function PainelAfiliado(){
  const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[requiresLogin,setRequiresLogin]=useState(false),[email,setEmail]=useState(""),[restricted,setRestricted]=useState(false),[feedback,setFeedback]=useState("");
  useEffect(()=>{affiliateDashboard().then(setData).catch(()=>setRequiresLogin(true)).finally(()=>setLoading(false))},[]);
  function continueLogin(){if(!email.trim())return;const params=new URLSearchParams({email:email.trim(),returnTo:"/afiliado"});window.location.href=`/login?${params}`}
  async function copy(url:string){await navigator.clipboard.writeText(url);setFeedback("Link copiado.");window.setTimeout(()=>setFeedback(""),2000)}
  async function share(url:string){if(navigator.share)await navigator.share({title:"Minha campanha SorteX",url});else await copy(url)}
  if(loading)return <main className="grid min-h-screen place-items-center bg-zinc-100"><div className="h-48 w-[min(90vw,480px)] animate-pulse rounded-3xl bg-white"/></main>;
  if(requiresLogin)return <main className="grid min-h-screen place-items-center bg-zinc-100 p-5"><section className="w-full max-w-md rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm font-black uppercase text-violet-700">Área de afiliados</p><h1 className="mt-2 text-3xl font-black">Entrar</h1><p className="mt-2 text-sm text-zinc-500">Acesse com a conta vinculada ao convite enviado pelo organizador.</p><label className="mt-6 block text-sm font-bold">E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@exemplo.com" className="mt-2 min-h-12 w-full rounded-xl border px-3"/></label><button type="button" disabled={!email.trim()} onClick={continueLogin} className="mt-4 min-h-12 w-full rounded-xl bg-violet-700 px-4 font-black text-white disabled:opacity-50">Continuar</button><button type="button" onClick={()=>setRestricted(value=>!value)} aria-expanded={restricted} className="mt-3 min-h-11 w-full rounded-xl border font-bold">Registrar-se</button>{restricted&&<div className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950"><strong>Cadastro restrito</strong><p className="mt-2">Cadastro disponível somente por convite.</p><p className="mt-2">Para se tornar afiliado é necessário receber um convite enviado pelo organizador. Entre em contato com o organizador para solicitar acesso.</p></div>}</section></main>;
  if(!data)return null;
  const cards=[["Cliques",data.clicks],["Conversões",data.conversions],["Pendente",money(data.pending)],["Disponível",money(data.available)],["Pago",money(data.paid)]];
  return <main className="min-h-screen bg-zinc-100 p-5 md:p-10"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase text-violet-700">SorteX Afiliados</p><h1 className="mt-2 text-3xl font-black">Seu painel de crescimento</h1><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-5">{cards.map(([label,value])=><div key={label} className="rounded-2xl bg-white p-5"><p className="text-sm text-zinc-500">{label}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</div><section className="mt-6 rounded-3xl bg-white p-6"><h2 className="text-xl font-black">Links e materiais de divulgação</h2>{data.links.length?<div className="mt-4 space-y-3">{data.links.map(link=><article key={link.id} className="rounded-2xl bg-zinc-50 p-4"><p className="font-black">{link.campaign?.title||"Campanha"}</p><p className="mt-2 break-all text-sm">{link.url}</p><p className="mt-2 text-xs text-zinc-500">{link.clicks} cliques · {link.conversions} conversões{link.commissionPercentage!=null?` · ${link.commissionPercentage}% de comissão`:""}</p><div className="mt-3 flex gap-2"><button onClick={()=>void copy(link.url)} className="min-h-11 rounded-xl border px-4 font-bold"><Copy className="mr-2 inline" size={17}/>Copiar link</button><button onClick={()=>void share(link.url)} className="min-h-11 rounded-xl bg-violet-700 px-4 font-bold text-white"><Share2 className="mr-2 inline" size={17}/>Compartilhar</button></div></article>)}</div>:<p className="mt-4 text-zinc-500">Nenhum link disponível. Aceite um convite para começar.</p>}{feedback&&<p aria-live="polite" className="mt-4 font-bold text-emerald-700">{feedback}</p>}</section></div></main>;
}

function money(value:number){return value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
