'use client';
import { useEffect, useState } from 'react';

type Mode='organizer'|'winners'|'buyer'|'admin';
type JsonRecord=Record<string,unknown>;
const card='rounded-3xl border border-violet-100 bg-white p-6 shadow-sm';
export default function DrawWorkspace({mode}:{mode:Mode}){
  const [items,setItems]=useState<JsonRecord[]>([]);const [message,setMessage]=useState('');const [campaignId,setCampaignId]=useState('');const [lotteryDrawId,setLotteryDrawId]=useState('');
  const endpoint=mode==='buyer'?'/api/draws/winners/my':mode==='winners'?'/api/draws/winners/organizer':mode==='admin'?'/api/draws/admin/lottery-draws':'/api/draws/admin/lottery-draws';
  useEffect(()=>{fetch(endpoint).then(r=>r.json()).then(v=>setItems(Array.isArray(v)?v:[])).catch(()=>setItems([]));},[endpoint]);
  async function action(path:string,body:unknown={}){setMessage('Processando...');const response=await fetch(`/api/draws/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();setMessage(response.ok?'Operação concluída com registro auditável.':result.message??'Não foi possível concluir.');if(response.ok&&mode==='admin'){const list=await fetch(endpoint).then(r=>r.json());setItems(Array.isArray(list)?list:[]);}}
  if(mode==='admin')return <Shell title="Resultados da Loteria Federal" subtitle="Cadastro manual, revisão e bloqueio administrativo."><LotteryForm onSubmit={async(data)=>action('admin/lottery-draws',data)}/><ItemList items={items}/></Shell>;
  if(mode==='buyer')return <Shell title="Meus prêmios" subtitle="Acompanhe entregas e confirme o recebimento com segurança."><ItemList items={items}/></Shell>;
  if(mode==='winners')return <Shell title="Ganhadores" subtitle="Contato, entrega, confirmação e material de divulgação."><ItemList items={items}/><div className={card}><h2 className="text-lg font-bold">Prévia vertical 9:16</h2><div className="mx-auto mt-4 aspect-[9/16] max-w-64 rounded-[2rem] bg-gradient-to-b from-violet-950 to-violet-600 p-5 text-white"><div className="flex justify-between text-xs"><span>LOGO ORGANIZADOR</span><b>SorteX</b></div><div className="flex h-full flex-col items-center justify-center text-center"><span className="text-5xl">🏆</span><h3 className="mt-4 text-2xl font-black">Prêmio entregue</h3><p className="mt-2">Verificado pela SorteX</p><div className="mt-8 rounded-xl bg-white/15 p-3 text-xs">QR CODE • código público</div></div></div></div></Shell>;
  return <Shell title="Motor de sorteios" subtitle="Simule, execute e confirme separadamente, com regra publicada e resultado verificado."><div className={card}><div className="grid gap-4 md:grid-cols-2"><Field label="ID da campanha" value={campaignId} onChange={setCampaignId}/><Field label="ID da extração verificada" value={lotteryDrawId} onChange={setLotteryDrawId}/></div><div className="mt-5 flex flex-wrap gap-3"><Button onClick={()=>action(`campaigns/${campaignId}/draw/simulate`,{lotteryDrawId})}>Simular</Button><Button onClick={()=>action(`campaigns/${campaignId}/draw/execute`,{lotteryDrawId})}>Executar prévia</Button><Button onClick={()=>action(`campaigns/${campaignId}/draw/confirm`)}>Confirmar resultado</Button></div>{message&&<p className="mt-4 rounded-xl bg-violet-50 p-3 text-sm text-violet-800">{message}</p>}</div><RuleSimulator/></Shell>;
}
function Shell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl"><span className="text-sm font-bold uppercase tracking-widest text-violet-600">SorteX • Módulo 6</span><h1 className="mt-2 text-3xl font-black text-slate-950">{title}</h1><p className="mt-2 text-slate-600">{subtitle}</p><div className="mt-8 grid gap-6">{children}</div></div></main>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<input className="rounded-xl border border-slate-200 p-3 font-normal" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Button({onClick,children}:{onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className="rounded-xl bg-violet-700 px-5 py-3 text-sm font-bold text-white transition hover:bg-violet-800">{children}</button>}
function ItemList({items}:{items:JsonRecord[]}){return <div className={card}><h2 className="text-lg font-bold">Registros</h2><div className="mt-4 grid gap-3">{items.length?items.map((item,index)=><pre key={String(item.id??index)} className="overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-emerald-300">{JSON.stringify(item,null,2)}</pre>):<p className="text-sm text-slate-500">Nenhum registro disponível.</p>}</div></div>}
function LotteryForm({onSubmit}:{onSubmit:(data:JsonRecord)=>Promise<void>}){const [values,setValues]=useState({extractionNumber:'',drawDate:'',firstPrize:'',secondPrize:'',thirdPrize:'',fourthPrize:'',fifthPrize:''});return <form className={card} onSubmit={e=>{e.preventDefault();void onSubmit({...values,sourceType:'MANUAL'});}}><h2 className="text-lg font-bold">Cadastrar extração</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Extração" value={values.extractionNumber} onChange={v=>setValues({...values,extractionNumber:v})}/><Field label="Data (ISO)" value={values.drawDate} onChange={v=>setValues({...values,drawDate:v})}/>{(['firstPrize','secondPrize','thirdPrize','fourthPrize','fifthPrize'] as const).map((key,i)=><Field key={key} label={`${i+1}º prêmio (5 dígitos)`} value={values[key]} onChange={v=>setValues({...values,[key]:v})}/>)}</div><div className="mt-4"><Button onClick={()=>undefined}>Salvar para revisão</Button></div></form>}
function RuleSimulator(){const [result,setResult]=useState<JsonRecord|null>(null);async function simulate(){const steps=[1,2,3,4,5].map((sourcePrize,order)=>({order:order+1,sourcePrize,digitPosition:'UNIT',direction:'NORMAL'}));const response=await fetch('/api/draws/draw-rules/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ruleDefinition:{version:1,outputLength:5,steps,normalization:{mode:'MODULO_TOTAL_NUMBERS'}},prizes:['12345','54321','00009','90807','11111'],totalNumbers:100000})});setResult(await response.json());}return <div className={card}><h2 className="text-lg font-bold">Simulador visual</h2><p className="mt-1 text-sm text-slate-500">Usa dados fictícios e nunca cria ganhador.</p><div className="mt-4"><Button onClick={simulate}>Executar simulação segura</Button></div>{result&&<pre className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-emerald-300">{JSON.stringify(result,null,2)}</pre>}</div>}
