"use client";
import { useCallback, useEffect, useState } from "react";
import { Gift, LoaderCircle, RotateCw } from "lucide-react";
import Button from "@/components/ui/Button";
type InstantResult={id:string;purchaseId:string;winningNumber:string;instantPrize:{description:string;value:number}};
type RouletteStatus={config:{enabled:boolean;name:string};totalRounds:number;availableRounds:number};
export default function PostPaymentRewards({campaignId,purchaseId}:{campaignId:string;purchaseId:string}){
 const [instant,setInstant]=useState<InstantResult[]>([]),[roulette,setRoulette]=useState<RouletteStatus|null>(null),[loading,setLoading]=useState(true),[spinning,setSpinning]=useState(false),[result,setResult]=useState<{itemName:string;isPrize:boolean}|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/draws/winners/my-instant-prizes",{credentials:"include"}),fetch(`/api/draws/roulette/campaigns/${campaignId}/status`,{credentials:"include"})]);if(a.ok){const rows=await a.json();setInstant((Array.isArray(rows)?rows:[]).filter((item:InstantResult)=>item.purchaseId===purchaseId))}if(b.ok)setRoulette(await b.json())}finally{setLoading(false)}},[campaignId,purchaseId]);
 useEffect(()=>{void load()},[load]);
 async function spin(){if(spinning)return;setSpinning(true);setError("");try{const response=await fetch(`/api/draws/roulette/campaigns/${campaignId}/spin`,{method:"POST",credentials:"include"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||"Não foi possível girar a roleta.");setResult(payload.result);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível girar a roleta.")}finally{setSpinning(false)}}
 if(loading)return <div className="mt-5 flex justify-center"><LoaderCircle className="animate-spin text-violet-700"/></div>;
 return <div className="mt-6 space-y-4">{instant.map(prize=><div key={prize.id} className="rounded-3xl bg-gradient-to-br from-amber-300 via-yellow-100 to-violet-200 p-1 shadow-xl"><div className="rounded-[20px] bg-white/90 p-6 text-center"><div className="text-5xl">🎉</div><p className="mt-2 text-sm font-black uppercase text-violet-700">Parabéns!</p><h3 className="text-2xl font-black">Você encontrou uma Cota Premiada</h3><div className="mt-4 grid gap-2 sm:grid-cols-3"><Info label="Número premiado" value={prize.winningNumber}/><Info label="Prêmio" value={prize.instantPrize.description}/><Info label="Valor" value={`R$ ${Number(prize.instantPrize.value).toFixed(2).replace(".",",")}`}/></div><p className="mt-4 text-sm text-zinc-600">Nossa equipe entrará em contato.</p></div></div>)}{roulette?.config.enabled&&roulette.totalRounds>0&&<div className="rounded-2xl border border-violet-200 bg-violet-50 p-5 text-center"><Gift className="mx-auto text-violet-700"/><h3 className="mt-2 text-xl font-black">{roulette.config.name}</h3><p className="mt-1 text-sm text-zinc-600">Você ganhou {roulette.totalRounds} rodada{roulette.totalRounds===1?"":"s"}. Disponíveis: {roulette.availableRounds}.</p>{result&&<div className={`mx-auto mt-4 max-w-sm rounded-xl p-4 font-black ${result.isPrize?"bg-amber-100 text-amber-900":"bg-white text-zinc-700"}`}>{result.isPrize?"🎉 ":""}{result.itemName}</div>}<Button className="mt-4" disabled={spinning||roulette.availableRounds<1} onClick={()=>void spin()}>{spinning?<LoaderCircle className="animate-spin"/>:<RotateCw size={17}/>} {roulette.availableRounds>0?"Girar agora":"Rodadas utilizadas"}</Button>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}</div>}</div>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white p-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 font-black">{value}</p></div>}
